### PR TITLE
Feature/vs2015

### PR DESCRIPTION
**Pull request by GreyMerlin**
## Add .sln and .vcprojx files to allow compilation with VS2015

/\* **_Background_**: I've been using "classic" WinMerge at least since 2.12.4 (in 2009) - my notes do not go back farther than that.  My latest version was 2.13.20 (with 10 small private patches).  I decided to get up-to-date and to join the GitHub community.   I was surprised at the divergent projects that now exist for WinMerge.  I picked this **sdottaka** fork because it has interesting extensions (especially 3-way compare and image compare) and because it is an active fork.  I only have VS2015 Community, so these proposed patches reflect my conversion of winmerge-v2 to use VS2015. \*/

These patches only **add** new **.sln** and **.vcxproj** files - **_no_** modifications are made to the existing files.  No modifications are made to the file tree structure, especially the BuildTmp/ and Build/ folders.  

New files are ...

- WinMerge_vs2015.sln
- Src/Merge_vs2015.vcprojx
- Src/MergeLang_vs2015.vcprojx
- Externals/poco/Foundataion/Foundation_vs2015.vcprojx
- Externals/poco/Util/Util_vs2015.vcprojx
- Externals/poco/XML/XML_vs2015.vcprojx
- Texting/GoogleTest/UnitTests/UnitTests_vs2015.vcprojx
- a few additions to .gitignore were also necessary.

Since a Compare of this Pull Request shows that all files appear to be completely new (which would make the changes **_very_** hard to review), I used a series of commits to show the progression from the original copies of the sln and vcxproj files into these new files; please see the individual commit comments for details.

I also made various changes to the actual compilation configuration attributes ...
- All projects now explicitly use Unicode.  Previously many still used MultiByte.
- All are set to Platform Tool Set = v140 and Target Platform = 10.0.14393.0.  Therefore WinXP compatible code files are not produced.
- Renamed the Solution Configurations so that they are all uniformly Release Unicode and Debug Unicode.  I eliminated all other Configurations.  The changes are identical for Win32 and x64.
- All compilations are now MultiProcessorCompilation enabled, which implies that MinimalRebuild is disabled.  There is some consensus (and my own personal experience with other projects) that this is faster (sometimes much faster) in a local development environment.
- I cleaned up various compilation Configuration settings to eliminate warnings about command line incompatibilities.

Testing ...
- This Feature/VS2015 branch is current as of the sdottaka **jp-130** release.
- All four variants (Win32 Release and Debug and x64 Release and Debug) are supported and tested.
- MergeLang and UnitTests both run correctly, with all four compilation configurations.
- I have made no changes/additions to the new Batch Files; they represent the workflow of sdottaka which I do not want to disturb. 
- I made no changes to the freeimage, frhed, sevenzip, or winimerge repositories.  I used the dll files provided with **winmerge-2.14.0-jp-130-x64-Setup-exe.zip** for all 64-bit testing.
- I made **_no_** changes to ShellExtension, nor did I attempt compilation or testing. /\* I have interesting local patches to ShellExtension, which I will convert and publish eventually; they require careful thought because of the new 3-way compare. \*/
- I made no changes to the Inno or Wix installers, **nor did I test them**.  Because I made no changes to the Build/ folder, they should work without problem.

I suspect that changing the Platform Tool Set to v140 could be controversial.  But I note that this is an **additional** compilation solution and makes **_no_** changes to the existing \*_vs100.\* compilation files.  

With VS2017 just now available (08 Mar 2017), I plan on a similar migration to that compiler after I upgrade my local working environment.

I look forward to working with sdottaka to make these patches acceptable.

Thank You !!

### CODE REVIEW

**Comment by sdottaka** [comment]
merged. Thank you for the PR.

**Comment by GreyMerlin** [comment]
I am confused:  Your reply says "merged...", but the status is "Closed with unmerged commits".  And the branch is clearly not merged (or perhaps not _yet_ merged)...

I am satisfied with either result, and perhaps I just need more patience, but ??

Thank you

**Comment by sdottaka** [comment]
Sorry ｄ

**Comment by GreyMerlin** [comment]
No Problem :) 
This was my first-ever PR on GitHub and I was uncertain of what to expect next.
Thank You !!

**Pull request merged**
